## Intro to TF and colab. Stuff Covered:

* Intro 2 tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* using @tf.function (a way to speed up regular Python functions)
* Use GPU's and TPU's.
* Exercises. Yay!

In [1]:
# Intro to Tensors


import tensorflow as tf

# Which version??
print(tf.__version__)

2.9.2


In [2]:
# Create Tensors

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimmensions of a tensor (ndim)

scalar.ndim

0

In [4]:
# Create a vector

vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimmension of the vector

vector.ndim

1

In [6]:
# Create a matrix (has more than 1 dimmension)

matrix = tf.constant([[10, 10],
                     [7, 7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 7,  7]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# New Matrix

new_matrix = tf.constant([[10., 7.],
                          [5., 67.],
                          [3., 56]], dtype=tf.float16)

new_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 5., 67.],
       [ 3., 56.]], dtype=float16)>

In [9]:
# Tensor

tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [10]:
tensor.ndim

3

In [11]:
# I hope it makes sense ;) 

changeable_tensor = tf.Variable([[10,7]])
unchangeable_tensor = tf.constant([[10, 7]])

## Creating Random Tensors:

* Are of some size which contain random numbers. 


In [12]:
# Create 2 random tensors

#A seed is a 1024-bit unsigned integer represented either as a Python integer or a vector of integers. Seeds shorter than 1024-bit will be padded.

#set the seed
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2


 # Are they Equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [13]:
# Shuffle a tensor

not_shuffled = tf.constant([[11., 33.],
                          [22., 44.],
                          [44., 66.]])
not_shuffled
not_shuffled.ndim


# Let'shuffle baby:

# Global Level
tf.random.set_seed(42)

# Operational Level
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[11., 33.],
       [22., 44.],
       [44., 66.]], dtype=float32)>

In [14]:
# Create tensors from NumPy arrays

# Create a tensor with all 1's.

tf.ones([10,7])

# Create a tensor with all 0's.
tf.zeros(shape=(10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [15]:
# Turn Numpy arrays into tensors

import numpy as np

# Create a np array from 1 -> 25

np_A = np.arange(1, 25, dtype=np.int32)

np_A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [16]:
 # Convert to a tensor:

A = tf.constant(np_A, shape=(2,3,4))
B = tf.constant(np_A)

A, B


(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [17]:
A.ndim

3

In [18]:
# Getting information from tensors
# The most important are: shape, rank, axis or dimmension, size

In [19]:
# Create a rank 4 tensor

rank4tf = tf.zeros(shape=[2,3,4,5])

rank4tf

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [20]:
rank4tf[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [21]:
rank4tf.shape, rank4tf.ndim, tf.size(rank4tf)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [22]:
# Get various attributes of our tensor

print("The datatype of every element:", rank4tf.dtype)
print("Number of dimmensions (rank):", rank4tf.ndim)
print("Elements along the 0 axis", rank4tf.shape[0])
print("Elements along the last axis:", rank4tf.shape[-1])
print("Total no. of elements", tf.size(rank4tf))
print("Total no. of elements", tf.size(rank4tf).numpy())

The datatype of every element: <dtype: 'float32'>
Number of dimmensions (rank): 4
Elements along the 0 axis 2
Elements along the last axis: 5
Total no. of elements tf.Tensor(120, shape=(), dtype=int32)
Total no. of elements 120


In [23]:
# Tensors can be indexed just like Python Lists

# Example: get the first 2 elements of each dimension

rank4tf[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [24]:
# Create a rank 2 tensor

rank2tf = tf.zeros(shape=[2,2])
rank2tf

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [25]:
rank2tf.shape, rank2tf.ndim

(TensorShape([2, 2]), 2)

In [26]:
 # Get the last two items of each of the row of our rank 2 tensor

rank2tf[:, -1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [27]:
# Add in extra dimmensions to our tensor

rank3tf = rank2tf[..., tf.newaxis]
rank3tf


<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

In [28]:
# Alternative way (-1 means the last axis)

tf.expand_dims(rank2tf, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[0.],
        [0.]],

       [[0.],
        [0.]]], dtype=float32)>

In [29]:
# Expand the zero axis:

tf.expand_dims(rank2tf, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[0., 0.],
        [0., 0.]]], dtype=float32)>

In [30]:
# Expand the middle axis:

tf.expand_dims(rank2tf, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=float32, numpy=
array([[[0., 0.]],

       [[0., 0.]]], dtype=float32)>

In [31]:
# Tensor Operations

# Basic Operations

tensor = tf.constant([[10,7],
                      [13, 14]])

tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [23, 24]], dtype=int32)>

In [32]:
# Multiplication

tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [130, 140]], dtype=int32)>

In [33]:
# Subtraction

tensor - 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7,  4],
       [10, 11]], dtype=int32)>

In [34]:
# We can also use tensorflow built-in functions too

tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [130, 140]], dtype=int32)>

In [35]:
# Matrix Multiplication

# It is one of the most common tensor operations.
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [13 14]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[191, 168],
       [312, 287]], dtype=int32)>

In [36]:
# Multiplication is doen element-wise
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [169, 196]], dtype=int32)>

In [37]:
# '@' is for matrix multiplication
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[191, 168],
       [312, 287]], dtype=int32)>

In [38]:
tensor.shape

TensorShape([2, 2])

In [39]:
# The dot product (Matrix multiplication)
# tf.matmul()
# tf.tensordot()

#!!OBS: we need to transpose one of the matrices in order to perform the dot product!!

In [40]:
X = tf.constant([[1,2],
                 [3, 4],
                 [5, 6]])

Y = tf.constant([[11,12],
                 [13, 14],
                 [15, 16]])

In [41]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14],
       [15, 16]], dtype=int32)>

In [42]:
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [43]:
# tf.tensordot() ---> transposed 

tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[125, 134],
       [164, 176]], dtype=int32)>

In [44]:
# tf.tensordot() --->reshaped  
tf.matmul(X, tf.reshape(Y, shape = (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 39,  42,  45],
       [ 89,  96, 103],
       [139, 150, 161]], dtype=int32)>

In [45]:
# Change the datatye of a tensor

B = tf.constant([3.4, 5.6])
B.dtype

tf.float32

In [46]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [47]:
# change to float 16 (works better with hardware. Faster.Stronger.)

D = tf.cast(B, dtype= tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([3.4, 5.6], dtype=float16)>,
 tf.float16)

In [48]:
# Change from int32 to float32

E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [49]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

In [50]:
## Aggregating Tensors 


D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [51]:
# Get the absolute value

tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [52]:
# Forms of aggreation of tensors:
# min
# max
# mean
# sum 

E = tf.constant(np.random.randint(0, 100, size=50))
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [53]:
# min

tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [54]:
# max

tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [55]:
# mean

tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [56]:
# sum 

tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2252>

In [63]:
import tensorflow_probability as tfp

# variance

tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=807>

In [ ]:
# variance without tfp

tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

In [62]:
# std Dev

tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.421091>

In [66]:
# Find the possitional minimum and max

tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [68]:
# Find pos. max

tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [69]:
# Index our largest value position

F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [72]:
# Check for equality

F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [73]:
# Find pos. min

tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [74]:
# index of our smallest position 

F[tf.argmin(F)]


<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [75]:
# Check for equality

F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [78]:
# Squeezing a tensor (Removing all single dimmensions)

tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [79]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [80]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [82]:
G_squeezed.shape


TensorShape([50])

In [84]:
# One hot encoding 

some_list = [0,1,2,3] # stands for red, green, blue, purple

tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [85]:
tf.one_hot(some_list, depth=4, on_value='ding', off_value='dong')


<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'ding', b'dong', b'dong', b'dong'],
       [b'dong', b'ding', b'dong', b'dong'],
       [b'dong', b'dong', b'ding', b'dong'],
       [b'dong', b'dong', b'dong', b'ding']], dtype=object)>

In [1]:
# Finding access to GPU 

import tensorflow as tf

tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
!nvidia-smi

Wed Oct 19 09:16:17 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------